-- SELF REFERENCING
CREATE TABLE CATEGORY (
    CatID INT PRIMARY KEY,
    ParentCatID INT,
    FOREIGN KEY (ParentCatID) REFERENCES CATEGORY(CatID)
);

-- M:N RELATIONSHIP
CREATE TABLE ORDER_ITEM (
    OrderID INT,
    ProductID INT,
    Quantity INT
);

-- MULTIVALUED ATTRIBUTE
CREATE TABLE CUSTOMER_EMAIL (
    CustID INT,
    Email VARCHAR(100)
);
